import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: '🚀 Getting Started',
      items: [
        'intro',
        'getting-started/quick-start',
        'getting-started/local-setup-ollama',
        'getting-started/authentication',
      ],
    },
    {
      type: 'category',
      label: '🏆 Why Choose WP LLM',
      items: [
        'comparison',
        'success-stories',
        'pricing',
      ],
    },
    {
      type: 'category',
      label: '📚 Core Concepts',
      items: [
        '01_concepts',
        '00_glossary',
        'capabilities',
        'models',
      ],
    },
    {
      type: 'category',
      label: '🔧 API Reference',
      items: [
        'api-reference',
        'api-reference/api-authentication',
        'api-reference/api-endpoints',
        'api-reference/api-errors',
        'api-reference/api-sdks',
      ],
    },
    {
      type: 'category',
      label: '🔗 Integrations',
      items: [
        'integrations/cursor-ide',
        'integrations/vs-code',
        'integrations/wp-cli',
        'integrations/github-actions',
        'integrations/webhooks',
      ],
    },
    {
      type: 'category',
      label: '🏗️ Development',
      items: [
        'examples',
        'advanced-usage',
      ],
    },
    {
      type: 'category',
      label: '⚡ Performance & Security',
      items: [
        'performance-optimization',
        'security-best-practices',
      ],
    },
    {
      type: 'category',
      label: '🏢 Enterprise',
      items: [
        'enterprise/enterprise-overview',
      ],
    },
    {
      type: 'category',
      label: '🛠️ Tools & Resources',
      items: [
        'troubleshooting',
        'deployment',
      ],
    },
    {
      type: 'category',
      label: '📖 Contributing',
      items: [
        'contributing/contributing-guide',
        'contributing/development-workflow',
      ],
    },
  ],
};

export default sidebars;
